services:
  mariadb:
    image: mariadb:11
    container_name: moim-mariadb
    environment:
      MARIADB_ROOT_PASSWORD: 1234
      MARIADB_DATABASE: moim
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "127.0.0.1", "-uroot", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 20
