# -----------------------------------------------------------------------------
# File: application-dev.yml
# Project: Moim Back-end
# Desc: Spring Boot application configuration in YAML format.
# Author: ChulJJA
# Created: 09.01.2025.
# Last Modified: 09.06.2025.
# -----------------------------------------------------------------------------

spring:
  # DB info
  datasource:
    url: jdbc:mariadb://localhost:3306/moim?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: 1234
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
        jdbc.time_zone: UTC # Ensures all dates/times are stored and queried in UTC.
  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true # Checks migration consistency before running.
    baseline-on-migrate: true # Allows Flyway to manage existing DBs.
    out-of-order: false # Prevents applying migrations out of sequence.

management:
  endpoints.web.exposure.include: health,info
  info:
    env:
      enabled: true

app:
  # JWT (JSON Web Toke) settings.
  jwt:
    issuer: moim-app
    secret: change-this-dev-secret-please
    access-token-minutes: 60
