# -----------------------------------------------------------------------------
# File: application-docker.yml
# Project: Moim Back-end
# Description: Spring Boot configuration for Docker environment.
# Author: ChulJJA
# Created: 09.01.2025
# Last Modified: 09.09.2025
# -----------------------------------------------------------------------------

spring:
  datasource:
    url: jdbc:mariadb://db:3306/moim?useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true
    baseline-on-migrate: true

app:
  # JWT (JSON Web Token) settings.
  jwt:
    issuer: moim-app
    secret: dl1cjf2tmd3!rkd4gus@rla5cks6gh7#rla8xo9gh9$
    access-token-minutes: 60