spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/moim?createDatabaseIfNotExist=true&serverTimezone=UTC
    username: root
    password: 1234
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration

management:
  endpoints.web.exposure.include: health,info

app:
  jwt:
    issuer: moim-app
    secret: change-this-dev-secret-please
    access-token-minutes: 60
