# -----------------------------------------------------------------------------
# File: application.yml
# Project: Moim Back-end
# Desc: Spring Boot application configuration in YAML format. Defines core
#       settings such as application name, server options, database connection,
#       profiles, and other environment-specific configurations.
# Author: ChulJJA
# Created: 09.01.2025.
# Last Modified: 09.06.2025.
# -----------------------------------------------------------------------------

spring:
  application:
    name: moim-backend
  profiles:
    active: dev # Spring Boot will load application-dev.yml (if present) alongside this file.
  security:
    user:
      name: clee
      password: 1234

server:
  port: 8080

logging:
  level:
    root: info
    org.springframework.web: info
    # your base package here:
    com.moim: debug
  file:
    name: logs/moim-backend.log

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,mappings
  endpoint:
    health:
      show-details: when_authorized

info:
  app:
    name: Moim Server
    description: Backend service for the Moim community platform
    version: 1.0.0
  author:
    name: ChulJJA
    email: cj.chuleee@gmail.com